### ISSUE TITLE
file structure for nc/ncml file

### ISSUE THREAD

**Issue by salme146** [zdefne-usgs/ocean-iso-metadata#22]
I think it would be good to include within the /project_name/ folder where the .ncml and .nc files should be so that the command line for ncml -> iso works as intended. This should also include where the units stylesheet should go.

**Comment by zdefne-usgs** [comment]
I have updated the Wiki to write out that the path to catalog.xml and the NCML file should be the same for ncISO to apply to the correct file. Udunits defaults to file named **udunits2_combined_whmsc.xml** under the same folder with the ncml file location. User can search and replace filename later only if necessary. That should be unlikely because this file should be the latest master file which should include all the units defined up to that date. updated the Wiki to include the default location of Udunits file.
